### ISSUE TITLE
Schedule-Distribution not found

### ISSUE THREAD

**Issue by lavolp3** [hbashton/spotify-ripper#24]
After trying to use after some time, I now get a python error. Completely new install didn't help
```
Traceback (most recent call last):
  File "/usr/local/bin/spotify-ripper", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2876, in <module>
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 449, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 745, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 639, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: schedule>=0.3.1
```

Installation found `schedule==0.4.2`

Running OSMC 2017.04-1 on Raspbian Jessie 8.0 on a RPi 3B

**Comment by lavolp3** [comment]
Sorry, issue resolved.
Removed the old version using pip and installed the new version using python.
Now it works again.
