### ISSUE TITLE
Exception in thread SpotifyRipperThread:

### ISSUE THREAD

**Issue by daweedm** [hbashton/spotify-ripper#25]
I'm running spotify-ripper with the php's `exec()`
```
    [9443] => Exception in thread SpotifyRipperThread:
    [9444] => Traceback (most recent call last):
    [9445] =>   File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    [9446] =>     self.run()
    [9447] =>   File "/usr/local/lib/python2.7/dist-packages/spotify_ripper/ripper.py", line 329, in run
    [9448] =>     self.post.clean_up_partial()
    [9449] =>   File "/usr/local/lib/python2.7/dist-packages/spotify_ripper/post_actions.py", line 247, in clean_up_partial
    [9450] =>     rm_file(ripper.audio_file)
    [9451] =>   File "/usr/local/lib/python2.7/dist-packages/spotify_ripper/utils.py", line 96, in rm_file
    [9452] =>     os.remove(file_name)
    [9453] => UnicodeEncodeError: 'ascii' codec can't encode character u'\xf8' in position 57: ordinal not in range(128)
    [9454] => 
    [9455] => Rip complete
    [9456] => Spotify error detected
    [9457] => 'ascii' codec can't encode character u'\xf8' in position 57: ordinal not in range(128)
```

It seems beeing a issue related to character encoding but I've already set theses env variables (php side):

```
putenv("PYTHONIOENCODING=utf-8");
putenv("LANG=en_US.UTF-8");
putenv("LANGUAGE=en_US:en");
putenv("LC_ALL=en_US.UTF-8");
```

I have the same env variable set in in Dockerfile :

```
ENV PYTHONIOENCODING utf-8
RUN locale-gen en_US.UTF-8
ENV LANG='en_US.UTF-8' LANGUAGE='en_US:en' LC_ALL='en_US.UTF-8'
```

Any ideas ? Thanks !

**Comment by duke8585** [comment]
I also have the problem, but only on my raspberry, not on the mac version...

EDIT: i thought it was also filenaming within my playlist, so i tried some single tracks with special character tracks. they all worked so i tried my initial commend for the whole playlist. now it works, strange, but this is fine ;)
