### ISSUE TITLE
When trying to download a single track (happened with most of them) I get this error

### ISSUE THREAD

**Issue by papajo-r** [hbashton/spotify-ripper#28]
I used all the steps mentioned here https://www.youtube.com/watch?v=b0U6q2lGHD8 (read the steps in the description under the video) downloading playlist works fine (although some songs dont download for some reason)

If I try to download a single track by getting its 21symbol "id" from spotify webplayer by entering this to my console 

`sudo spotify-ripper -u myspotifyusernamehere spotify:track:5VyPKrrpiLVwcvBAtQnbm2`

I get this error and I get it with any track I tried to download. (I have premium and as said the playlists mostly download fine.. the last 130 track play-list i downloaded had successfully downloaded 126 tracks) 

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.7/dist-packages/spotify_ripper-2.9.1-py2.7.egg/spotify_ripper/ripper.py", line 232, in run
    audio_file = self.format_track_path(idx, track)
  File "/usr/local/lib/python2.7/dist-packages/spotify_ripper-2.9.1-py2.7.egg/spotify_ripper/ripper.py", line 604, in format_track_path
    track.load()
  File "/usr/local/lib/python2.7/dist-packages/pyspotify-2.0.5-py2.7-linux-x86_64.egg/spotify/track.py", line 81, in load
    return utils.load(self._session, self, timeout=timeout)
  File "/usr/local/lib/python2.7/dist-packages/pyspotify-2.0.5-py2.7-linux-x86_64.egg/spotify/utils.py", line 242, in load
    _check_error(obj)
  File "/usr/local/lib/python2.7/dist-packages/pyspotify-2.0.5-py2.7-linux-x86_64.egg/spotify/utils.py", line 206, in _check_error
    error_type, ignores=[spotify.ErrorType.IS_LOADING])
  File "/usr/local/lib/python2.7/dist-packages/pyspotify-2.0.5-py2.7-linux-x86_64.egg/spotify/error.py", line 31, in maybe_raise
    raise LibError(error_type)
LibError: General permanent error

```

**Comment by papajo-r** [comment]
Is that something I can hope for being fixed ? Is there an issue with the code or with my linux setup? should I try something that maybe would fix this?

**Comment by ghost** [comment]
What OS are you using?
