### ISSUE TITLE
Raspberry Pi 3 : Problem with appkey

### ISSUE THREAD

**Issue by chicungunya** [hbashton/spotify-ripper#60]
Hello guys,
I'm trying to make a convert but it doesn't work I have this error : 

`pi@raspberrypi:~ $ spotify-ripper -u user spotify:track:52xaypL0Kjzk0ngwv3oBPR
 Spotify Ripper - v2.9.1
  Encoding output:	MP3, CBR 320 kbps
  Spotify bitrate:	320 kbps
  Unicode support:	ASCII only
  Output directory:	/media/pi/WD/Musique
  Settings directory:	/home/pi/.spotify-ripper
  Format String:	{album_artist}/{year} {album}/Disc 0{disc_idx}/0{track_idx} {track_name}.{ext}
  Overwrite files:	No
Traceback (most recent call last):
  File "/usr/local/bin/spotify-ripper", line 11, in <module>
    load_entry_point('spotify-ripper==2.9.1', 'console_scripts', 'spotify-ripper')()
  File "/usr/local/lib/python2.7/dist-packages/spotify_ripper-2.9.1-py2.7.egg/EGG-INFO/scripts/main.py", line 510, in main
    ripper = Ripper(args)
  File "/usr/local/lib/python2.7/dist-packages/spotify_ripper-2.9.1-py2.7.egg/spotify_ripper/ripper.py", line 110, in __init__
    config.load_application_key_file(app_key_path)
  File "/usr/local/lib/python2.7/dist-packages/pyspotify-2.0.5-py2.7-linux-armv7l.egg/spotify/config.py", line 131, in load_application_key_file
    self.application_key = fh.read()
  File "/usr/local/lib/python2.7/dist-packages/pyspotify-2.0.5-py2.7-linux-armv7l.egg/spotify/config.py", line 113, in application_key
    'Invalid application key; expected 321 bytes, got %d bytes' % size)
AssertionError: Invalid application key; expected 321 bytes, got 65032 bytes`

Do I miss something ? 

Thanks

**Comment by ghost** [comment]
Your appkey file is invalid. Go here: [richardk80/spotify-ripper](https://github.com/richardk80/spotify-ripper), download my appkey file and replace the one you have with that. Should work then. If it doesn't then let me know.
