### ISSUE TITLE
Exception in thread SpotifyRipperThread

### ISSUE THREAD

**Issue by Smoltbob** [hbashton/spotify-ripper#7]
When trying to rip, I get the following error 
`Exception in thread SpotifyRipperThread:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.7/dist-packages/spotify_ripper/ripper.py", line 222, in run
    audio_file = self.format_track_path(idx, track)
  File "/usr/local/lib/python2.7/dist-packages/spotify_ripper/ripper.py", line 577, in format_track_path
    track.load()
  File "/usr/local/lib/python2.7/dist-packages/spotify/track.py", line 81, in load
    return utils.load(self._session, self, timeout=timeout)
  File "/usr/local/lib/python2.7/dist-packages/spotify/utils.py", line 246, in load
    raise spotify.Timeout(timeout)
Timeout: Operation did not complete in 10.000s`

This error didn't occur when I last used this nice script, a few months ago.

**Comment by Smoltbob** [comment]
Running as root fixed this.
